service: email-manager-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage,'dev'}
  region: eu-west-2

plugins:
  - serverless-plugin-typescript

functions:
  listener:
    handler: handler.listener
    events:
      - stream:
          arn: arn:aws:kinesis:eu-west-2:628555153221:stream/events-dev
          batchSize: 100
          startingPosition: LATEST
          enabled: true
